### ISSUE TITLE
install kableextra

### ISSUE THREAD

**Issue by jimhshen** [J-PAL/admindatahandbook#22]
Adding kableExtra to the libraries.R file doesn't work, with the following error:

ERROR: dependencies ‘xml2’, ‘httr’ are not available for package ‘rvest’
* removing ‘/usr/local/lib/R/site-library/rvest’
ERROR: dependencies ‘xml2’, ‘rvest’ are not available for package ‘kableExtra’
* removing ‘/usr/local/lib/R/site-library/kableExtra’

The downloaded source packages are in
	'/tmp/Rtmp2Sey11/downloaded_packages'
Quitting from lines 49-50 (_main.Rmd) 
Error in FUN(X[[i]], ...) : Package not found
Calls: <Anonymous> ... withVisible -> eval -> eval -> sapply -> lapply -> FUN

**Comment by larsvilhuber** [comment]
@jimhshen Have a look at [this workflow file](https://github.com/labordynamicsinstitute/covid19-expectations-data/blob/master/.github/workflows/main.yml). The key is to use the rocker/r-apt Docker image, and install the R packages that are required using the apt package manager, which handles most of the dependencies (in terms of R packages and system libraries). The rest should work as before (however, you need to manually coordinate the apt install vs. the "library()" calls for now, until this can be shifted to a config file.

Give it a try, I'll review.

**Comment by jimhshen** [comment]
Was trying this out on my fork to avoid breaking anything on the main repository, looks like the r-apt:disco image doesn't come with pandoc?

Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).

from the last run I tried: https://github.com/jimhshen/admindatahandbook/runs/977683556?check_suite_focus=true

**Comment by larsvilhuber** [comment]
apt install -y pandoc

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by larsvilhuber** [comment]
Read the workflow file I point to: 
- it calls `Rscript --vanilla _programs/master.R ubuntu `
- `master.R` in turn has a bunch of install commands, see [these lines](https://github.com/labordynamicsinstitute/covid19-expectations-data/blob/e30c3962c024e8f74c486fbb55e27af6515e4ae6/_programs/master.R#L9). 

The point of using r-apt:disco is to be able to use "apt install" commands for most R packages, and any dependencies. If you install `rmarkdown`, it *should* install `pandoc` as a dependency, but might not.

By switching to this docker, you *must* replace all `install.packages()` commands with the equivalent `apt install` commands, otherwise you are no more advanced than before.

**Comment by jimhshen** [comment]
Tried updating it some more. Gets past the build stage now, except there is an error saying "E: Unable to locate package r-cran-kableExtra" that seems concerning. However, fails on deploy:

  fatal: A branch named 'gh-pages' already exists.
  ##[error]Action failed with "The process '/usr/bin/git' failed with exit code 128"

https://github.com/jimhshen/admindatahandbook/runs/982403145?check_suite_focus=true

**Comment by jimhshen** [comment]
Sidestepping the problem for now by using atusydown.

https://hub.docker.com/r/atusy/atusydown
https://github.com/atusy/atusydown
